export const TIME_UNITS = ['minutes', 'hours', 'days', 'weeks', 'months', 'years'];
export const WEEKDAYS = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
export const RELATIVE_DAYS = ['yesterday', 'today', 'tomorrow'];
export const RELATIVE_WEEKS = ['this week', 'next week', 'last week'];
export const RELATIVE_MONTHS = ['this month', 'next month', 'last month'];
export const RELATIVE_YEARS = ['this year', 'next year', 'last year'];
export const RELATIVE_WEEKENDS = ['this weekend', 'next weekend', 'last weekend'];
export const GENERAL_TIME_UNITS = ['midnight', 'noon'];
export const TIME_OF_DAY = ['8am', '9am', '10am', '11am', '12pm', '1pm', '2pm', '3pm', '4pm', '5pm', '6pm', '7pm', '8pm', '9pm', '10pm', '11pm', '12am', '1am', '2am', '3am', '4am', '5am', '6am', '7am'];